Repository CSC510-Team87/PopcornPicks, pull requests merged in 2024-11, with the labels that each got.

#33 Merging the updated recommendation system into dev
  src/prediction_scripts/model.py
  src/recommenderapp/app.py
Labels: enhancement

#34 Implement Movie Watchlist Page and Watchlist Button
  frontend/src/app/components/watchlist-button.tsx
  frontend/src/app/landing/page.tsx
  frontend/src/app/search/page.tsx
  frontend/src/app/watchlist/page.tsx
  package-lock.json
  src/init.sql
  src/recommenderapp/app.py
  src/recommenderapp/static/script.js
  src/recommenderapp/templates/landing_page.html
Labels: enhancement

#40 Fixed bugs in the profile and review page
  frontend/src/app/profile/page.tsx
  frontend/src/app/review/page.tsx
  src/movies.py
  src/recommenderapp/app.py
  src/recommenderapp/utils.py
Labels: bug, enhancement

#41 Add Test Suite for Watchlist
  .github/workflows/unittest.yml
  test/test_watchlist.py
Labels: Testing
